package com.vprooks.urgLibJavaWrapper;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : urg_tcpclient.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class urg_tcpclient_t extends Structure {
    /**
     * C type : sockaddr_in
     */
    public UrgLib.sockaddr_in server_addr;
    public int sock_desc;
    public int sock_addr_size;
    /**
     * C type : ring_buffer_t
     */
    public ring_buffer_t rb;
    /**
     * C type : char[RB_SIZE]
     */
    public byte[] buf = new byte[(int) UrgLib.RB_SIZE];
    /**
     * for pushed back char
     */
    public int pushed_back;

    public urg_tcpclient_t() {
        super();
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("server_addr", "sock_desc", "sock_addr_size", "rb", "buf", "pushed_back");
    }

    /**
     * @param server_addr C type : sockaddr_in<br>
     * @param rb          C type : ring_buffer_t<br>
     * @param buf         C type : char[RB_SIZE]<br>
     * @param pushed_back for pushded back char
     */
    public urg_tcpclient_t(UrgLib.sockaddr_in server_addr, int sock_desc, int sock_addr_size, ring_buffer_t rb, byte buf[], int pushed_back) {
        super();
        this.server_addr = server_addr;
        this.sock_desc = sock_desc;
        this.sock_addr_size = sock_addr_size;
        this.rb = rb;
        if ((buf.length != this.buf.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.buf = buf;
        this.pushed_back = pushed_back;
    }

    public urg_tcpclient_t(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends urg_tcpclient_t implements Structure.ByReference {

    }

    public static class ByValue extends urg_tcpclient_t implements Structure.ByValue {

    }
}
