package com.vprooks.urgLibJavaWrapper;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : urg_connection.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class urg_connection_t extends Structure {
    /**
     * @see UrgLib.urg_connection_type_t
     * !<  Type of connection<br>
     * C type : urg_connection_type_t
     */
    public int type;
    /**
     * !<  Serial connection<br>
     * C type : urg_serial_t
     */
    public urg_serial_t serial;
    /**
     * !<  Ethernet connection<br>
     * C type : urg_tcpclient_t
     */
    public urg_tcpclient_t tcpclient;

    public urg_connection_t() {
        super();
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("type", "serial", "tcpclient");
    }

    /**
     * @param type      @see urg_connection_type_t<br>
     *                  !<  Type of connection<br>
     *                  C type : urg_connection_type_t<br>
     * @param serial    !<  Serial connection<br>
     *                  C type : urg_serial_t<br>
     * @param tcpclient !<  Ethernet connection<br>
     *                  C type : urg_tcpclient_t
     */
    public urg_connection_t(int type, urg_serial_t serial, urg_tcpclient_t tcpclient) {
        super();
        this.type = type;
        this.serial = serial;
        this.tcpclient = tcpclient;
    }

    public urg_connection_t(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends urg_connection_t implements Structure.ByReference {

    }

    public static class ByValue extends urg_connection_t implements Structure.ByValue {

    }
}

